auth:
  type: DISABLED

management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus"

springdoc:
  path: /swagger 
  api-docs:
    enabled: true
  swagger-ui:
    url: /openapi/kafbat-ui-api.yaml
    urls:
      - name: kafbat-ui
        url: /openapi/kafbat-ui-api.yaml
    config-url: null 
  override-with-generic-response: true

logging:
  level:
    root: INFO
    io.kafbat.ui: DEBUG
    reactor.netty.http.server.AccessLog: INFO
    org.hibernate.validator: WARN

