name: "Infra: PR block merge"
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  block_merge:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@388fd6af37b34cdfe5a23b37060e763217e58b03 # https://github.com/mheap/github-action-required-labels/releases/tag/5.5.0
        with:
          mode: exactly
          count: 0
          labels: >
            status/blocked,
            status/needs-attention,
            status/on-hold,
            status/pending,
            status/triage,
            status/pending-backend,
            status/pending-frontend,
            status/pending-QA
