name: "Infra: CVE checks"
on:
  pull_request:
    types: [ "opened", "reopened", "synchronize" ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'api/**'
      - 'gradle/**'
      - 'Dockerfile'
      - 'build.gradle'
      - 'settings.gradle'
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'api/**'
      - 'gradle/**'
      - 'Dockerfile'
      - 'build.gradle'
      - 'settings.gradle'
  workflow_dispatch:
  schedule:
    - cron: '0 8 15 * *'

permissions:
  contents: read

jobs:
  check-cves:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build project
        id: build
        run: |
          ./gradlew clean build \
          -x test \
          -Pbuild-docker-images=true \
          -Pinclude-frontend=true \
          -Pversion=latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: api
          platforms: linux/amd64
          push: false
          load: true
          tags: |
            ghcr.io/kafbat/kafka-ui:latest
          build-args: |
            JAR_FILE=build/libs/api-latest.jar
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Run CVE checks
        uses: aquasecurity/trivy-action@v0.29.0
        with:
          image-ref: "ghcr.io/kafbat/kafka-ui:latest"
          format: "table"
          exit-code: "1"

  notify:
    needs: check-cves
    if: ${{ always() && needs.check-cves.result == 'failure' && github.event_name == 'schedule' }}
    uses: ./.github/workflows/infra_discord_hook.yml
    with:
      message: "Attention! CVE checks run failed! Please fix them CVEs :("
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL_CVE }}
