name: "Infra: CVE checks"

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 8 15 * *'

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - name: get branch name
        id: extract_branch
        run: |
          tag='build-${{ github.sha }}'
          echo "tag=${tag}" >> $GITHUB_OUTPUT

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'maven'

      - name: Build project
        id: build
        run: |
          ./mvnw -B -ntp versions:set -DnewVersion=$GITHUB_SHA
          ./mvnw -B -V -ntp clean package -DskipTests
          export VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        uses: ./.github/workflows/docker_build.yml
        with:
          tag: ${{ steps.extract_branch.outputs.tag }}
          version: ${{ steps.build.outputs.version }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          repository: ghcr.io/kafbat/kafka-ui
          build-context: api

      - name: Run CVE checks
        uses: aquasecurity/trivy-action@0.19.0
        with:
          image-ref: "ghcr.io/kafbat/kafka-ui:${{ steps.build.outputs.version }}"
          format: "table"
          exit-code: "1"
