name: "Infra: CVE checks"
on:
  pull_request:
    types: [ "opened", "reopened", "synchronize" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 8 15 * *'

permissions:
  contents: read

jobs:

  check-cves:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # https://github.com/actions/checkout/releases/tag/v6.0.1
        with:
          token: ${{ github.token }}

      - name: Set up JDK
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # https://github.com/actions/setup-java/releases/tag/v4
        with:
          java-version-file: '.java-version'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build project
        id: build
        run: |
          ./gradlew clean build \
          -x test \
          -Pbuild-docker-images=true \
          -Pinclude-frontend=true \
          -Pversion=latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # https://github.com/docker/setup-qemu-action/releases/tag/v3.7.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # https://github.com/docker/setup-buildx-action/releases/tag/v3.11.1

      - name: Cache Docker layers
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # https://github.com/actions/cache/releases/tag/v4.3.0
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build docker image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # https://github.com/docker/build-push-action/releases/tag/v6.18.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: api
          platforms: linux/amd64
          push: false
          load: true
          tags: |
            ghcr.io/kafbat/kafka-ui:latest
          build-args: |
            JAR_FILE=build/libs/api-latest.jar
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Run CVE checks
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # https://github.com/aquasecurity/trivy-action/releases/tag/0.33.1
        with:
          image-ref: "ghcr.io/kafbat/kafka-ui:latest"
          format: "table"
          exit-code: "1"

  notify:
    needs: check-cves
    if: ${{ always() && needs.build-and-test.result == 'failure' && github.event_name == 'schedule' }}
    uses: ./.github/workflows/infra_discord_hook.yml
    with:
      message: "Attention! CVE checks run failed! Please fix them CVEs :("
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL_CVE }}
