name: "E2E: PR healthcheck"
on:
  pull_request:
    types: [ "opened", "reopened", "synchronize" ]
    paths:
      - "pom.xml"
      - "contract/**"
      - "api/**"
      - "serde-api/**"
      - "frontend/**"
      - "e2e-tests/**"

permissions:
  contents: read
  checks: write
  statuses: write

jobs:
  build-and-test:
    uses: ./.github/workflows/e2e-run.yml
    secrets: inherit
    with:
      suite_name: "smoke"
      sha: ${{ github.event.pull_request.head.sha }}
