name: "Frontend: build and test"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  tests:
    env:
      CI: true
      NODE_ENV: dev
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # https://github.com/actions/checkout/releases/tag/v6.0.1
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ github.token }}

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # https://github.com/pnpm/action-setup/releases/tag/v4.2.0
        with:
          version: 9.15.4

      - name: Install node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # https://github.com/actions/setup-node/releases/tag/v4
        with:
          node-version: "22.12.0"
          cache: "pnpm"
          cache-dependency-path: "./frontend/pnpm-lock.yaml"

      - name: Install Node dependencies
        run: |
          cd frontend/
          pnpm install --frozen-lockfile

      - name: Compile
        run: |
          cd frontend/
          pnpm compile

      - name: Linter
        run: |
          cd frontend/
          pnpm lint:CI

      - name: Tests
        run: |
          cd frontend/
          pnpm test:CI

      # TODO check frontend sonar results in sonarcloud after migration to gradle
