name: 'Discord hook'

on:
  workflow_call:
    inputs:
      message:
        description: 'Message text'
        required: true
        type: string
    secrets:
      DISCORD_WEBHOOK_URL:
        required: true

permissions:
  contents: read

jobs:

  hook:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord on Failure
        uses: Ilshidur/action-discord@d2594079a10f1d6739ee50a2471f0ca57418b554 # https://github.com/Ilshidur/action-discord/releases/tag/0.4.0
        with:
          args: ${{ inputs.message }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
