name: 'Discord hook'

on:
  workflow_call:
    inputs:
      message:
        description: 'Message text'
        required: true
        type: string
    secrets:
      DISCORD_WEBHOOK_URL:
        required: true

permissions:
  contents: read

jobs:

  hook:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord on Failure
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9 # https://github.com/Ilshidur/action-discord/releases/tag/0.3.2
        with:
          args: ${{ inputs.message }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
