name: "Infra: Release: Serde API"

on: workflow_dispatch

permissions:
  contents: read

jobs:
  release-serde-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # infered from @v4
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Set up JDK
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # infered from @v4
        with:
          java-version-file: '.java-version'
          distribution: 'zulu'
          cache: 'gradle'

      - id: install-secret-key
        name: Install GPG secret key
        run: |
          cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import

      - name: Publish to Maven Central
        # TODO fix me next publish, I'm broken :(
        run: |
          mvn source:jar javadoc:jar package gpg:sign \
          -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} \
          -Dserver.username=${{ secrets.NEXUS_USERNAME }} \
          -Dserver.password=${{ secrets.NEXUS_PASSWORD }} \
          central-publishing:publish -pl serde-api -s settings.xml
