# Docs: https://github.com/gradle/actions/blob/main/docs/wrapper-validation.md
name: "Validate Gradle Wrapper"

on:
  push:
    paths:
      - gradle/wrapper/gradle-wrapper.jar
  pull_request:
    paths:
      - gradle/wrapper/gradle-wrapper.jar

jobs:
  validation:
    name: "Validate Gradle Wrapper"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # https://github.com/actions/checkout/releases/tag/v6.0.2
      - uses: gradle/actions/wrapper-validation@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # https://github.com/gradle/actions/releases/tag/v5.0.0
